module.exports = rules = {
  CAN_CREAT_PRODUCT: "CAN_CREAT_PRODUCT",
  CAN_CREATE_COUPONS: "CAN_CREATE_COUPONS",
  CAN_MANAGE_ORDERS: "CAN_MANAGE_ORDERS",
  CAN_MANAGE_DELAYED: "CAN_MANAGE_DELAYED",
  CAN_CREATE_SLIDERS: "CAN_CREATE_SLIDERS",
  CAN_MANAGE_CARDS: "CAN_MANAGE_CARDS"
};
